# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

autoload -U colors && colors
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="mytheme"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#
# git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
# zsh-syntax-highlighting =>  In .zshrc source "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-completions docker docker-compose)




# ======================== Key ==============================
# ===========================================================
#autoload -U compinit
#compinit
autoload -Uz compinit && compinit -u

alias terproxy-1081="export ALL_PROXY='socks5://127.0.0.1:1081'"
alias terproxy-1080="export ALL_PROXY='socks5://127.0.0.1:1080'"
alias unsetproxy="unset ALL_PROXY"
#alias myip="curl ifconfig.me"
alias myip="curl cip.cc"
alias audio="alsamixer"
alias audio-on="amixer sset Master unmute"
alias cat="ccat"
alias dockerRUN="systemctl start docker"
alias pandoc-PDF='pandoc --pdf-engine=xelatex -V CJKmainfont="HYLuoHuaShi" -V mainfont="Source Code Pro" -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" --highlight-style tango'
alias ll="ls -l"
alias la="ls -a"
alias bufClear="sync | echo 3 > /proc/sys/vm/drop_caches"
alias terminalizer_Gif="terminalizer render $1 -o $(date +%H-%M-%S-%Y)"
alias terminalizer_Rec="terminalizer record"
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ls='ls --color=auto'

alias transfer_UpFile=transfer
transfer(){
	curl -H "Max-Downloads: $2" -H "Max-Days: $3" --upload-file "$1" https://transfer.sh/$(basename "$1") | tee /dev/null;
	echo
}

# ---------- git -----------

# 进一步改进ls的彩色输出功能，比如损坏的符号链接显示为红色
eval $(dircolors -b)

eval "$(lua $HOME/Downloads/z.lua/z.lua  --init zsh once enhanced)"
export NNN_CONTEXT_COLORS='2456'
# ===========================================================
#export LC_ALL=C.UTF-8
export LANG=C.UTF-8

# ===========================================================
# --------- Docker for Pentesters
# From: https://blog.ropnop.com/docker-for-pentesters/#usefuldockeraliases

alias dockershell="docker run --rm -i -t --entrypoint=/bin/bash"  
alias dockershellsh="docker run --rm -i -t --entrypoint=/bin/sh"

function dockershellhere() {  
    dirname=${PWD##*/}
    docker run --rm -it --entrypoint=/bin/bash -v `pwd`:/${dirname} -w /${dirname} "$@"
}
function dockershellshhere() {  
    dirname=${PWD##*/}
    docker run --rm -it --entrypoint=/bin/sh -v `pwd`:/${dirname} -w /${dirname} "$@"
}

# ==========================================================

source $ZSH/oh-my-zsh.sh
# source ~/.bash_profile

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
source "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
